services:
  db:
    image: postgres:18.3-alpine
    container_name: bond_sports
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bond_sports
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d password"]
      interval: 5s
      timeout: 5s
      retries: 5


  testing_db:
    image: postgres:18.3-alpine
    container_name: bond_sports_testing
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bond_sports_testing
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d password"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: